name: Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
      - run: npm install
      - run: npm run package
      - uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: release/Vorn-Windows.exe

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
      - run: npm install
      - run: npm run package
        env:
          CSC_IDENTITY_AUTO_DISCOVERY: 'false'
      - uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: release/Vorn-macOS.dmg

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
      - run: npm install
      - run: npm run package
      - uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: release/Vorn-Linux.AppImage
